"""
Batch-level time series augmentations for contrastive pre-training.

All functions operate on tensors of shape [B, T, C] and are GPU-compatible.
Two independent calls to the returned callable produce two different stochastic
views of the same batch, as required by SupCon / SimCLR-style training.

Physical motivation for smell / gas-sensor data:
  jitter         — electronic noise inherent in every sensor reading
  scale          — gain drift between sessions or hardware units
  time_shift     — variable delay between smell presentation and recording start
  window_slice   — different sub-windows of the gas response carry the same label
  magnitude_warp — smooth baseline drift during a long measurement session
"""

from __future__ import annotations

import inspect
from typing import Callable, List

import torch
import torch.nn.functional as F


# ---------------------------------------------------------------------------
# Individual augmentations  (all take [B, T, C] → [B, T, C])
# ---------------------------------------------------------------------------

def jitter(x: torch.Tensor, sigma: float = 0.03) -> torch.Tensor:
    """Add independent Gaussian noise to every timestep and channel."""
    return x + torch.randn_like(x) * sigma


def scale(x: torch.Tensor, sigma: float = 0.1) -> torch.Tensor:
    """Randomly scale the amplitude of each sample independently."""
    factor = 1.0 + torch.randn(x.shape[0], 1, 1, device=x.device, dtype=x.dtype) * sigma
    return x * factor


def time_shift(x: torch.Tensor, max_shift: int = 50) -> torch.Tensor:
    """Circular-shift the time axis by a random amount in [-max_shift, max_shift]."""
    shift = int(torch.randint(-max_shift, max_shift + 1, (1,)).item())
    return torch.roll(x, shift, dims=1)


def window_slice(x: torch.Tensor, reduce_ratio: float = 0.9) -> torch.Tensor:
    """
    Crop a random contiguous sub-window and stretch it back to the original
    length via linear interpolation.  Each sample gets an independently chosen
    start index.
    """
    B, T, C = x.shape
    keep = max(int(T * reduce_ratio), 1)
    starts = torch.randint(0, max(T - keep, 1) + 1, (B,))
    out = torch.empty_like(x)
    for i in range(B):
        sliced = x[i, starts[i]: starts[i] + keep, :]      # [keep, C]
        resampled = F.interpolate(
            sliced.T.unsqueeze(0),                          # [1, C, keep]
            size=T,
            mode="linear",
            align_corners=False,
        ).squeeze(0).T                                      # [T, C]
        out[i] = resampled
    return out


def identity(x: torch.Tensor) -> torch.Tensor:
    """No-op augmentation — returns the input unchanged."""
    return x


def magnitude_warp(
    x: torch.Tensor,
    sigma: float = 0.2,
    num_knots: int = 4,
) -> torch.Tensor:
    """
    Multiply each sample by a smooth random curve generated by linearly
    interpolating between `num_knots` random amplitudes centred at 1.
    The curve is shared across all C channels within a sample.
    """
    B, T, C = x.shape
    knots = 1.0 + torch.randn(B, 1, num_knots, device=x.device, dtype=x.dtype) * sigma
    curve = F.interpolate(knots, size=T, mode="linear", align_corners=False)
    return x * curve.permute(0, 2, 1)   # [B, T, 1] broadcasts over C


# ---------------------------------------------------------------------------
# Registry and composer
# ---------------------------------------------------------------------------

_AUGMENTATIONS: dict[str, Callable] = {
    "jitter": jitter,
    "scale": scale,
    "time_shift": time_shift,
    "window_slice": window_slice,
    "magnitude_warp": magnitude_warp,
    "none": identity,
}

_DEFAULT_AUG_LIST = ["jitter", "scale", "time_shift", "magnitude_warp"]


def get_augmentation(
    aug_list: List[str] | None = None,
    **kwargs,
) -> Callable[[torch.Tensor], torch.Tensor]:
    """
    Return a callable that applies ONE randomly chosen augmentation from
    `aug_list` each time it is called.

    Two independent calls on the same batch produce two different stochastic
    views, which is what the contrastive trainer requires.

    Args:
        aug_list: Names of augmentations to sample from.
                  Defaults to ["jitter", "scale", "time_shift", "magnitude_warp"].
        **kwargs: Optional overrides for augmentation hyperparameters
                  (e.g. sigma=0.05, max_shift=30).
    """
    names = aug_list or _DEFAULT_AUG_LIST
    unknown = set(names) - _AUGMENTATIONS.keys()
    if unknown:
        raise ValueError(
            f"Unknown augmentation(s): {unknown}. "
            f"Choose from {list(_AUGMENTATIONS.keys())}."
        )
    fns = [_AUGMENTATIONS[n] for n in names]

    def _apply(x: torch.Tensor) -> torch.Tensor:
        idx = int(torch.randint(len(fns), (1,)).item())
        fn = fns[idx]
        sig = inspect.signature(fn).parameters
        filtered = {k: v for k, v in kwargs.items() if k in sig}
        return fn(x, **filtered)

    return _apply


__all__ = [
    "identity",
    "jitter",
    "scale",
    "time_shift",
    "window_slice",
    "magnitude_warp",
    "get_augmentation",
]
